import Head from 'next/head'
import Header from '../components/Header'
import Presentation from '../components/Presentation'
import Subtitle from '../components/Subtitle'
import styles from '../styles/Home.module.css'
import componentStyles from '../styles/Components.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossOrigin />
        <link
          href='https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap'
          rel='stylesheet'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <img
        src='https://res.cloudinary.com/dklpyhteh/image/upload/v1661311355/Portfolio/Ellipse1_chkzjb.png'
        className={styles.ellipse1}
      />
      <Header />
      <Presentation />
      <div className={componentStyles.section_spacer}>
        <Subtitle subtitle='< Sobre mi />' />
        <p className={componentStyles.paragraph}>
          Mi nombre es Jonathan David García González. Soy desarrollador web y backend, especializado en la creación de aplicaciones con React.js y de APIs REST con Node.js. Además, soy estudiante de Inglés y de Ingeniería de sistemas.
          Me apasiona todo lo relacionado con la tecnología, la programación, crear y el aprendizaje de cosas nuevas. Por eso decidí estudiar esta carrera, ya que tengo grandes proyectos en mente que deseo desarrollar a lo largo de mi vida.
          Más allá de la programación, me encanta hacer actividad física, viajar, los videojuegos y la música.
          Al final de esta página dejo un formulario de contacto, siéntete libre de usarlo en caso de que desees que forme parte de tu equipo, o para lo que necesites; así como de visitar mis redes sociales.
        </p>
      </div>
    </div>
  )
}
